server:
  port: 9000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Para Docker (default): http://keycloak:8080/realms/tpi-backend
          # Para desarrollo local: http://localhost:8081/realms/tpi-backend
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/tpi-backend}

  cloud:
    gateway:
      routes:

        - id: clientes
          uri: http://backend:8080
          predicates:
            - Path=/clientes/**

        - id: contenedores
          uri: http://backend:8080
          predicates:
            - Path=/contenedores/**

        - id: solicitudes
          uri: http://backend:8080
          predicates:
            - Path=/solicitudes/**

        - id: rutas
          uri: http://backend:8080
          predicates:
            - Path=/rutas/**

        - id: tramos
          uri: http://backend:8080
          predicates:
            - Path=/tramos/**

        - id: camiones
          uri: http://backend:8080
          predicates:
            - Path=/camiones/**

        - id: depositos
          uri: http://backend:8080
          predicates:
            - Path=/depositos/**

        - id: tarifas
          uri: http://backend:8080
          predicates:
            - Path=/tarifas/**
