services:

  mysql:
    image: mysql:8.0
    container_name: mysql_logistica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logistica_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - logistica-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_logistica
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - logistica-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logistica-backend
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/logistica_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      KEYCLOAK_URL: http://keycloak:8080
    ports:
      - "8080:8080"
    networks:
      - logistica-net
    
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: logistica-gateway
    restart: always
    depends_on:
      - backend
    ports:
      - "9000:9000"
    networks:
      - logistica-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    networks:
      - logistica-net

networks:
  logistica-net:

volumes:
  mysql_data:
